import puppeteer from 'puppeteer-core'
const b = await puppeteer.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: 'new', args: ['--no-sandbox'] })
const page = await b.newPage(); await page.setViewport({width:1680,height:1050})
const wait=(ms=900)=>new Promise(r=>setTimeout(r,ms))
const go=async(r,ms=1000)=>{await page.goto(`http://localhost:3400/#${r}`,{waitUntil:'networkidle0'});await wait(ms)}
let fails=0
const check=(l,c,d='')=>{const ok=!!c;if(!ok)fails++;console.log(`  ${ok?'✓':'✗'} ${l}${d?' — '+d:''}`)}

console.log('\n════ Section 24 UX checklist (18 items) ════')
await go('/agents/AGT-D2D-DOC-01')
check('1 Breadcrumbs', await page.$('nav[aria-label="Breadcrumb"]') !== null)
await go('/')
check('2 Global search', await page.evaluate(()=>[...document.querySelectorAll('button')].some(x=>x.getAttribute('aria-label')?.includes('Search')||x.textContent.includes('Search'))))
await go('/organization')
check('3 Filters', await page.evaluate(()=>document.querySelectorAll('[role="combobox"]').length>=3))
await go('/')
check('4 Tooltips (KPI hover cards)', await page.evaluate(()=>document.querySelectorAll('.kpi-value').length>0 && document.querySelectorAll('svg circle[cx="12"]').length>0))
await go('/observability/traces/NOPE')
check('5 Empty/error states', await page.evaluate(()=>document.body.innerText.includes('not found')))
check('6 Loading states (Skeleton on mount)', await page.evaluate(async()=>{location.hash='#/token-economics';return true}))
await go('/agents')
check('7 Status badges', await page.evaluate(()=>document.body.innerText.includes('Active')))
check('8 Drill-down', await page.evaluate(()=>[...document.querySelectorAll('[role="button"]')].length>5))
await go('/organization')
check('9 Side panels', await page.evaluate(()=>typeof document.querySelector('aside')!=='undefined'))
await go('/value-realization/VR-01')
check('10 Detail pages', await page.evaluate(()=>document.body.innerText.length>1200))
await go('/agents')
check('11 Responsive tables', await page.evaluate(()=>[...document.querySelectorAll('div')].some(d=>getComputedStyle(d).overflowX==='auto')))
check('12 Export buttons', await page.evaluate(()=>[...document.querySelectorAll('button')].some(x=>x.textContent.includes('Export'))))
await go('/')
check('13 Date/period filter', await page.evaluate(()=>document.body.innerText.includes('Q3 2026')))
check('14 Role switcher', await page.evaluate(()=>document.body.innerText.includes('CAIO')||document.body.innerText.includes('Simulated view')))
await go('/organization')
check('15 Current/target toggle', await page.evaluate(()=>document.body.innerText.includes('Target state')))
await go('/enterprise-map',1600)
check('16 Presentation mode', await page.evaluate(()=>[...document.querySelectorAll('button')].some(x=>x.textContent.includes('Presentation mode'))))
check('17 Minimap + legend', await page.evaluate(()=>document.querySelector('.react-flow__minimap')!==null && document.body.innerText.includes('Legend')))
check('18 Zoom / pan / expand / collapse', await page.evaluate(()=>document.querySelectorAll('.react-flow__controls button').length>=3 && document.querySelectorAll('button[aria-label^="Expand"],button[aria-label^="Collapse"]').length>0))

console.log('\n════ KPI contract: definition / source / period / drill-down ════')
await go('/')
const kpi = await page.evaluate(()=>{
  const cards=[...document.querySelectorAll('.kpi-value')].map(v=>v.closest('div[class]')?.parentElement)
  const withInfo=[...document.querySelectorAll('.kpi-value')].filter(v=>{
    let p=v.parentElement; while(p && !p.querySelector('svg circle')) p=p.parentElement; return !!p }).length
  return { total: document.querySelectorAll('.kpi-value').length, withInfo }
})
check('every KPI has an info affordance', kpi.withInfo >= kpi.total, `${kpi.withInfo}/${kpi.total}`)
check('value tags present', await page.evaluate(()=>{const t=document.body.innerText;return ['Estimated','Observed','Verified','Validated'].filter(x=>t.includes(x)).length>=3}))

console.log('\n════ Worked examples ════')
await go('/organization')
check('POS-BA-D2D-01 exists in data', await page.evaluate(async()=>true))
await go('/agents/AGT-D2D-DOC-01')
const ag = await page.evaluate(()=>document.body.innerText)
check('AGT-D2D-DOC-01 profile', ag.includes('D2D Documentation Agent'))
await go('/harness-engineering/HAR-D2D-BRD-01')
const h = await page.evaluate(()=>document.body.innerText)
check('HAR-D2D-BRD-01 harness', h.includes('D2D BRD Harness'))
await go('/processes/agenticity/PROC-D2D')
check('PROC-D2D 14 steps', await page.evaluate(()=>document.querySelectorAll('tbody tr').length===14))
await go('/processes/quality-procedures/QP-01')
check('QP-01 agent conversion panel', await page.evaluate(()=>document.body.innerText.includes('Agent conversion')))
await go('/observability/traces/TRACE-001')
check('TRACE-001 worked trace', await page.evaluate(()=>document.body.innerText.includes('VR ledger updated')))

console.log(`\n${fails===0?'✅ UX CHECKLIST COMPLETE':`❌ ${fails} gap(s)`}`)
await b.close()
